Feature_Servicio_Usuarios_y_metodos closed #60
FBS-UNA/SCT_FRONTEND pull request #61
Opened 2023-04-15 10:20 UTC by Biron2465

Se cera el servicio, además, se crea la interfas de usuario y el metodo de getUsuarios

2023-04-15 23:59 UTC, Jared2910 commented on src/app/SCT/interfaces/usuario.interface.ts
Se hubiera ahorrado el crear otro archivo y pone esa interfaz en la misma que la del Usuario

2023-04-16 00:02 UTC, Jared2910 requested changes

2023-04-16 00:02 UTC, Jared2910 commented on src/app/SCT/interfaces/usuario.interface.ts
Se hubiera ahorrado el crear otro archivo y pone esa interfaz en la misma que la del Usuario

2023-04-16 01:25 UTC, vito2312 approved these changes

2023-04-16 01:25 UTC, vito2312 commented on src/app/SCT/interfaces/usuario.interface.ts
Creo que lo hizo solo por no tener que tocar mas la interfaz usuario, pero asi vale!

2023-04-16 03:29 UTC, Jared2910 approved these changes

2023-04-16 03:30 UTC, Jared2910 commented on src/app/SCT/interfaces/usuario.interface.ts
Vamonos así sin mezcla y sin nada

2023-04-16 19:51 UTC, merged